name: setup-docker

on:
  pull_request:

jobs:
  setup-docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Run setup script
        run: |
          ./setup-dev-env.sh -y -v docker
